[target.x86_64-unknown-linux-gnu]
rustflags = [
    "-C", "linker=g++",
    "-C", "link-arg=-fuse-ld=ld.lld",
    "-L", "/usr/local"
]

[target.x86_64-unknown-linux-musl]
rustflags = [
    "-C", "linker=g++",
]
