[target.x86_64-unknown-linux-gnu]

rustflags = [
    "-C", "linker=gcc",
	"-L", "/usr/lib",
]

[target.x86_64-unknown-linux-musl]
rustflags = [
    "-C", "linker=gcc",
	"-L", "/usr/lib",

]

[target.'cfg(target_arch = "x86_64")'.dependencies]
sld2 = ["sdl2"]

[target.'cfg(target_arch = "x86_64")'.dependencies.sdl2]
git = "https://github.com/rust-sdl2/rust-sdl2"
default-features = false
features = ["ttf","image","gfx","mixer","static-link","bundled"]

#[target.x86_64-unknown-linux-gnu.dependencies.sdl2]
#git = "https://github.com/rust-sdl2/rust-sdl2"
#default-features = false
#features = ["ttf","image","gfx","mixer","static-link","bundled"]
#
#[target.x86_64-unknown-linux-musl.dependencies.sdl2]
#git = "https://github.com/rust-sdl2/rust-sdl2"
#default-features = false
#features = ["ttf","image","gfx","mixer","static-link","bundled"]
