[target.x86_64-unknown-linux-gnu]
rustflags = [
    "-C", "linker=g++",
    "-L", "/usr/include/x86_64-linux-gnu"
]

[target.x86_64-unknown-linux-musl]
rustflags = [
    "-C", "linker=g++",
    "-L", "/usr/include/x86_64-linux-gnu"
]
