[target.x86_64-unknown-linux-gnu]
rustflags = [
    "-C", "linker=g++",
]
dependencies = ["sdl2"]

[target.x86_64-unknown-linux-musl]
rustflags = [
    "-C", "linker=g++",
]

[target.x86_64-unknown-linux-gnu.dependencies.sdl2]
git = "https://github.com/rust-sdl2/rust-sdl2"
default-features = false
features = ["ttf","image","gfx","mixer","static-link","bundled"]

[target.x86_64-unknown-linux-musl.dependencies.sdl2]
git = "https://github.com/rust-sdl2/rust-sdl2"
default-features = false
features = ["ttf","image","gfx","mixer","static-link","bundled"]
