[target.x86_64-unknown-linux-gnu]
rustflags = [
    "-C", "linker=g++",
]


[target.x86_64-unknown-linux-musl]
rustflags = [
    "-C", "linker=g++",
]

[target.'cfg(target-family "gnu")'.dependencies.sdl2]
git = "https://github.com/rust-sdl2/rust-sdl2"
default-features = false
features = ["ttf","image","gfx","mixer","static-link","bundled"]

[target.'cfg(target-family "musl")'.dependencies.sdl2]
git = "https://github.com/rust-sdl2/rust-sdl2"
default-features = false
features = ["ttf","image","gfx","mixer","static-link","bundled"]
