[target.x86_64-unknown-linux-gnu]
rustflags = [
    "-C", "linker=g++",
]

[dependencies.sdl2]
version = "0.36"
default-features = false


[target.x86_64-unknown-linux-musl]
rustflags = [
    "-C", "linker=g++",
]

