name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  x86_64-unknown-linux-gnu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install SDL2
      run: sudo apt-get update && sudo apt-get upgrade && sudo apt-get install libsdl2-2.0-0 libsdl2-dev libsdl2-gfx-dev libsdl2-mixer-dev libsdl2-ttf-dev libsdl2-image-dev && sudo dnf install sdl2-devel && yum install SDL2-devel
    - name: Install libunwind
      run: sudo apt-get update && sudo apt-get upgrade && sudo apt-get install libunwind-dev
    - name: Update linkers
      run: sudo apt-get install 'clang*' ldc lld '*sdl2*static*'
    - name: Import
      run: $PWD/import.sh
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: x86_64-unknown-linux-gnu
        override: true
    - uses: actions-rs/cargo@v1
      with:
        use-cross: true
        command: run
        args: --target x86_64-unknown-linux-gnu

        
  x86_64-unknown-linux-musl:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install SDL2
      run: sudo apt-get update && sudo apt-get upgrade && sudo apt-get install libsdl2-dev libsdl2-2.0-0 libsdl2-gfx-dev libsdl2-mixer-dev libsdl2-ttf-dev libsdl2-image-dev
    - name: Install libunwind
      run: sudo apt-get update && sudo apt-get upgrade && sudo apt-get install libunwind-dev
    - name: Update linker
      run: sudo apt-get install 'clang*' ldc lld
    - name: Import
      run: $PWD/import.sh
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: x86_64-unknown-linux-musl
        override: true
    - uses: actions-rs/cargo@v1
      with:
        use-cross: true
        command: run
        args: --target x86_64-unknown-linux-musl

