name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  aarch64:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Show Directory
      run: ls
    - name: Show Directory Name
      run: echo $PWD
    - name: Import
      run: $PWD/import.sh
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: aarch64-linux-android
        override: true
    - uses: actions-rs/cargo@v1
      with:
        use-cross: true
        command: run
        args: --target aarch64-linux-android
