name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Show Directory
      run: ls
    - name: Show Directory Name
      run: echo $PWD
    - name: Test 'la' command
      run: la import.sh
    - name: Import
      run: /home/runner/Rustemon/Rustemon/import.sh
    - uses: actions/checkout@v3
    - name: Build
      run: cargo run --release
