name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: ShowDir
      run: echo $PWD
    - uses: actions/checkout@v3
    - name: Build
      run: cargo run --release
