name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  aarch64:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Show Directory
      run: ls
    - name: Show Directory Name
      run: echo $PWD
    - name: Import
      run: $PWD/import.sh
    - uses: actions-rs/toolchain@v1
    - name: aarch64 Target
      run: rustup target add aarch64-linux-android
    - uses: actions-rs/cargo@v1
    - name: Run
      run: cargo xbuild --release --target=aarch64-linux-android
