name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  x86_64-unknown-linux-gnu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install libunwind and SDL2
      run: sudo apt-get update && sudo apt-get upgrade && sudo apt-get install libunwind-dev 'libsdl2*'
    - name: Ensure linker is up-to-date
      run: sudo apt-get install 'clang*' ldc lld
    - name: Import
      run: $PWD/import.sh
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: x86_64-unknown-linux-gnu
        override: true
    - uses: actions-rs/cargo@v1
      with:
        use-cross: true
        command: build
        args: --release --target x86_64-unknown-linux-gnu
    - name: Upload binary
      run: mkdir $PWD/binaries && mv $PWD/target/x86_64-unknown-linux-gnu/release/pokemon_structs $PWD/binaries/Rustemon-V.N-x86_64-unknown-linux-gnu && git add binaries/Rustemon-*-x86_64-unknown-linux-gnu && git commit -m "Built gnu binary" && git push

        
  x86_64-unknown-linux-musl:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install libunwind and SDL2
      run: sudo apt-get update && sudo apt-get upgrade && sudo apt-get install libunwind-dev 'libsdl2*'
    - name: Ensure linker is up-to-date
      run: sudo apt-get install 'clang*' ldc lld
    - name: Import
      run: $PWD/import.sh
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: x86_64-unknown-linux-musl
        override: true
    - uses: actions-rs/cargo@v1
      with:
        use-cross: true
        command: build
        args: --release --target x86_64-unknown-linux-musl
    - name: Upload binary
      run: mkdir $PWD/binaries && mv $PWD/target/x86_64-unknown-linux-musl/release/pokemon_structs $PWD/binaries/Rustemon-V.N-x86_64-unknown-linux-musl && git add binaries/Rustemon-*-x86_64-unknown-linux-musl && git commit -m "Built musl binary" && git push


